### PR TITLE
updating CLA links

### PR DESCRIPTION
**Pull request by highvoltag3**
Update CLA links in `CONTRIBUTING.MD` to use the new CLA system

### CODE REVIEW

**Comment by dagguh** [comment]
@highvoltag3 nice, thanks! I appreciate the form of PR 🙂 

We use strict CI checks for all PRs. Passing CI should be as easy as integrating signing up for TravisCi/CircleCI.
You don't have to do this, we can copy your branch on our forks and reuse our CI. But it might reduce friction in other repos as you go.

**Comment by mzyromski-atlassian** [comment]
@highvoltag3 are you planning to fix the CI or would you like me to take over by migrating the change to my fork and merging from there? I'm more than OK with the latter.

Also, I guess we should apply similar changes to `CONTRIBUTING.MD` in other JPT repositories as the CLA handling change is global and applies to all open source projects, doesn't it?

**Comment by mzyromski-atlassian** [comment]
https://ecosystem.atlassian.net/browse/JPERF-644

**Comment by highvoltag3** [comment]
> @highvoltag3 are you planning to fix the CI or would you like me to take over by migrating the change to my fork and merging from there? I'm more than OK with the latter.
Hi @mzyromski-atlassian feel free to take it over, thanks for the help there.


> Also, I guess we should apply similar changes to CONTRIBUTING.MD in other JPT repositories as the CLA handling change is global and applies to all open source projects, doesn't it?
Yes, thank you for putting the ticket in your backlog.

Cheers!

P.S: Feel free to close this when you take it over.

**Comment by mzyromski-atlassian** [comment]
I moved your commit to my fork: #16.

**Pull request closed without merging**
