### PR TITLE
updating CLA links

### PR DESCRIPTION
**Pull request by mzyromski-atlassian**

### CODE REVIEW

**Comment by mzyromski-atlassian** [comment]
@highvoltag3 Here's your commit (#15) moved to my fork so that we can have green CI.

**Comment by mzyromski-atlassian** [comment]
Unfortunately CI is red due to https://ecosystem.atlassian.net/browse/JPERF-645.

**Comment by dagguh** [comment]
> 'apt-get update -qq' returned a non-zero code: 100

`apt-get`, the main flake in JPT

**Comment by mzyromski-atlassian** [comment]
> > 'apt-get update -qq' returned a non-zero code: 100
> 
> `apt-get`, the main flake in JPT

This time it looks like it's a permanent failure though. I've rerun the branch >5 times already. Same problem on master.

**Comment by mzyromski-atlassian** [comment]
Rebased on master with ITs fix.

**Pull request merged**
